# Generated by Django 3.1.7 on 2021-03-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('reservation_start', models.DateTimeField()),
                ('reservation_end', models.DateTimeField()),
                ('customer_surname', models.TextField(max_length=40)),
                ('reservation_code', models.CharField(default='', max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='---', max_length=20, unique=True)),
                ('ground_level', models.IntegerField(default=0, max_length=2)),
                ('allowed_smoking', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('number_of_seats', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='---', max_length=20, unique=True)),
                ('special_annotation', models.CharField(default='', max_length=254)),
            ],
        ),
    ]
