# Generated by Django 3.1.7 on 2021-04-25 17:03

import bookings.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('floor', models.IntegerField(default=0)),
                ('smoking_allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='bookings.section')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reservation_code', models.CharField(default=bookings.models.generate_reservation_code, max_length=9, unique=True)),
                ('firstname', models.TextField(max_length=40)),
                ('lastname', models.TextField(max_length=40)),
                ('customer_email', models.EmailField(max_length=254)),
                ('category', models.CharField(blank=True, choices=[('Casual', 'Casual'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Other', 'Other')], max_length=15)),
                ('annotation', models.CharField(blank=True, default='', max_length=254)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='bookings.table')),
            ],
        ),
    ]
