# Generated by Django 3.1.7 on 2021-03-25 22:50

import bookings.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.IntegerField(default=1)),
                ('code', models.CharField(default='', max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='---', max_length=20, unique=True)),
                ('ground_level', models.IntegerField(default=0)),
                ('allowed_smoking', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_tables', to='bookings.table')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('reservation_start', models.TimeField()),
                ('reservation_end', models.TimeField()),
                ('customer_firstname', models.TextField(max_length=40)),
                ('customer_lastname', models.TextField(max_length=40)),
                ('customer_email', models.EmailField(max_length=254)),
                ('reservation_type', models.CharField(choices=[('C', 'Casual'), ('B', 'Birthday'), ('A', 'Anniversary'), ('O', 'Other')], max_length=1)),
                ('special_annotation', models.CharField(default='', max_length=254)),
                ('reservation_code', models.CharField(default=bookings.models.generate_reservation_code, max_length=9, unique=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_tables', to='bookings.table')),
            ],
        ),
    ]
