# Generated by Django 3.1.7 on 2021-04-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20210425_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='annotation',
            field=models.TextField(blank=True, max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('start', 'end', 'table'), ('end', 'table'), ('start', 'table')},
        ),
    ]
